title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          category:
            type: text
          client:
            type: text
          link:
            type: url
          text:
            type: textarea

  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        image:
          ration: 1/1
