title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          text:
            label: Project description
            type: textarea
            required: true
          year:
            type: number
            width: 1/2
          category:
            type: select
            options:
              - Product Design
              - Animals
              - Photo
              - Art
            width: 1/2
          client:
            type: text
            width: 1/2
            icon: user
          link:
            type: url
            width: 1/2
          tags:
            type: tags
          location:
            type: locator

  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        template: gallery-image
        image:
          ration: 1/1
